# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'Check actor permission'
description: 'A GitHub Action to check actor permission on the current repository.'
author: 'skjnldsv'

# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'user-x'
  color: 'purple'

inputs:
  token:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true
  require:
    description: Test whether the user meets the required permission
    required: false

outputs:
  result:
    description: Require result
  user-permission:
    description: User permission

runs:
  using: 'node12'
  main: 'dist/index.js'
